name: Deploy Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: Tests Workflow
    branches: main
    types: completed

jobs:
  tag:
    if: github.event.workflow_run.conclusion == 'success' && github.repository == 'ti2travel/travel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/bump@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: 'Github Action Job'
          email: 'engineering@tourconnect.com'
          branch: main
  publish:
    if: github.repository == ‘ti2travel/travel’
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
